server:
  port: 8080

spring:
  application:
    name: ginkgo-id-metaserver
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ginkgo_id?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.aurifolia.cloud.id.metaserver.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
  scan:
    base-packages: org.aurifolia.cloud.id.metaserver.service.impl

logging:
  level:
    org.aurifolia.cloud.id.metaserver: debug
