CREATE DATABASE IF NOT EXISTS ginkgo_id DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE ginkgo_id;

CREATE TABLE IF NOT EXISTS segment_meta (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '自增主键ID',
    biz_tag VARCHAR(64) NOT NULL UNIQUE COMMENT '业务标签',
    next_segment_number BIGINT NOT NULL DEFAULT 0 COMMENT '下一个可用号段编号',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_biz_tag (biz_tag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='号段元数据表';
